name: Publish Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: Authenticate to npm
        run: npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Install deps
        run: npm ci

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Publish package
        run: npm publish --access public